## **Scope rules**
-------

**When in different places of the code functions/variables with same name are defined, how does Python decides to select one among them??**    
**Each variable name belongs to a certain abstract environment aka namespace**   
      
**When having to select one among many identically named variables/functions Python uses _Scope rules_    
Python searches for the object with provided name, layer by layer, moving from inner layers towards outer layers and uses the first object it encounters with the provided variable name**

**Scope rules are represented by the acronym LEGB which stands for:     
&emsp; &emsp; &emsp; &emsp; &emsp; L - Local: the current function you are in       
&emsp; &emsp; &emsp; &emsp; &emsp; E - Enclosing function: the function that called the current function       
&emsp; &emsp; &emsp; &emsp; &emsp; G - Global: the module in which the function was defined       
&emsp; &emsp; &emsp; &emsp; &emsp; B - Built-in: Python's defaults**

**If Python cannot find the object with requested name anywhere it raises a `name error exception`.**

In [3]:
def update():
    x.append(1)

In [5]:
update()

NameError: name 'x' is not defined

**`NameError: name 'x' is not defined`**

In [6]:
x = [1,2]

In [7]:
update()

In [8]:
x # updated

[1, 2, 1]

**Python first looked for the variable `x` inside the function `update` but couldn't find any inside the `local` scope, then it skips the `enclosing function` scope since it is absent, and moves to `global` scope which indeed has the `x` variable. Since this is the first object with the requested name, Python will use this object**


In [13]:
def update(n,x):
    n = 2  # local variable
    x.append(4)
    print("update: ",n,x) 

In [14]:
def main(): # enclosing function for the update() function
    n = 1  # local variable
    x = [0,1,2,3]  # local variable
    print("main: ",n,x)
    update(n,x)  # update() function is called within the main() function
    print("main: ",n,x)

In [16]:
main()

main:  1 [0, 1, 2, 3]
update:  2 [0, 1, 2, 3, 4]
main:  1 [0, 1, 2, 3, 4]


**In the `main()` function `n,x` are defined locally; exist only inside the scope of that function.    
At the first `print` statement Python will print the locally defined variables    
Then the `update()` function is called form the local scope: which modifies the locally declared `x` not `n`   
`Update()` then prints the modified object `x` from the enclosing function's scope and `n` from its own local scope sine that `n` is the first `n` Python finds according to LEGB rule, not the enclosing function `main()`'s `n` variable     
`n = 1` defined under `main()`'s local scope cannot be modified by the enclosed `update()`'s `n = 2` definition: integer objects are immutable   
But the list `x` can be modified by `update()`'s `x.append(4)` call, since lists are mutable  
Then Python returns to the enclosing function from the enclosed function  
Then the second print statement returns the unmodified variable `n` and the modified list `x` from the local scope of enclosing `main()` function**

In [18]:
def increment(n):
    n += 1
    print(n)

n = 1
increment(n)
print(n)

2
1


**While `n` is defined globally on line 3, it is also defined locally in `increment`. Therefore, the function will print one greater than 1 due to the function and its argument, but the local `n` will not change.**

In [32]:
def increment(n):
    n += 1

In [37]:
n = 1

while n < 10:
    n = increment(n)
print(n)

None


TypeError: '<' not supported between instances of 'NoneType' and 'int'

**`'<' not supported between instances of 'NoneType' and 'int'` thrown since `increment()` doesn't return an output; this its output is of type `NoneType`**

In [38]:
def increment(n):
    n += 1
    return n

In [40]:
n = 1

while n < 10:
    n = increment(n)
print(n)

10


`return(n)` will ensure that the function returns the value. This new value will be assigned to `n`. The while loop will continue until the condition is met.

### **Classes and object oriented programming**
-----------

**When an exisiting object type does not fully satisfy the needs a new object type can be created known as a `class`.   
Often when a new type of object is created it will most definitely share certain characters with pre-existing object types.   
This brings inheritance, which is fundamental to OOP.    
Inheritance means defining a new object type (a new class) that inherits properties from existing object types**

**e.g. A new class can be defined that does everything what Python's default `list` does, in additional methods that satisfy our needs**

In [67]:
my_list = [2,6,43,7,6,7,8,243,3]  # a lsit object

In [61]:
my_list.sort() # sorts the original list

In [62]:
my_list

[2, 3, 6, 6, 7, 7, 8, 43, 243]

## **New classes are defined using the `class` statement**

In [ ]:
class MyList(list):
    # pending definitions
    

### Name of the class `"MyList"` immediately follows the word `class`.   
**MyList is followed by paranthesis, on order to specify inheritance;     
When a new class is created via inheritance the new class inherits the attributes defined for the base class (the class it's inheriting attributes from); in this clase a `list` class.**

**`class` statement specifies the internal structure of the new class, what methods & operations are supported.   
This does not create a new object of the newly defined class type.  
When an object of a particular type (class) is created that object is sometimes called an _instance_ of that class.    
This is similar to defining functions using `def`, which just defines what that function does when called but does not invoke the function!**

In [54]:
min(my_list) # minimum value in the list

2

In [56]:
max(my_list) # maximum value in the list

243

In [68]:
my_list

[2, 6, 43, 7, 6, 7, 8, 243, 3]

In [69]:
my_list.remove(243)  # remove() removes elements form list objects

In [70]:
my_list

[2, 6, 43, 7, 6, 7, 8, 3]

**When an element occurs multiple times in a list `remove()` removes only the first element**   

In [72]:
my_list  # has two 7s

[2, 6, 43, 7, 6, 7, 8, 3]

In [73]:
my_list.remove(7)

In [76]:
my_list  # note that only the first 7 is removed

[2, 6, 43, 6, 7, 8, 3]

In [78]:
class MyList(list):
    def remove_min(self):
        self.remove(min(self))  # min() finds the minimum & remove() removes that minimum value
    def remove_max(self):
        self.remove(max(self))  # max() finds the maximum & remove() removes that maximum value

Functions defined inside classes are known as instance methods as they operate on an instance of a class.   
e.g **`remove_min()`, `remove_max()`**  
By convention the name of the class instance is called `self` and it is always passes as the first argument of functions defined as part of a class.    


In [79]:
x = [3,23,5,12,5,6,67,8,456,8,4,2,9,0,12]
X = ["John","James","Lolly","Molly",67,2,123,6,87,"Grace","Rosalia"]

In [82]:
y = MyList(x)  # creating a new MyList class object by copying the elements of list object x

In [84]:
y

[3, 23, 5, 12, 5, 6, 67, 8, 456, 8, 4, 2, 9, 0, 12]

In [87]:
type(y)

__main__.MyList

In [90]:
dir(x)

['__add__',
 '__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [89]:
dir(y)

['__add__',
 '__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__module__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'remove_max',
 'remove_min',
 'reverse',
 'sort']

**Note the presence of `'remove_max'`, `'remove_min'` methods in addition to the default methods for `list` objects.**

In [92]:
dir(x) == dir(y)

False

In [103]:
set(dir(x)).symmetric_difference(set(dir(y)))  # methods that are not present in both classes (list & MyList)

{'__dict__', '__module__', '__weakref__', 'remove_max', 'remove_min'}

In [105]:
y

[3, 23, 5, 12, 5, 6, 67, 8, 456, 8, 4, 2, 9, 0, 12]

In [107]:
y.remove_min()

In [109]:
y  # 2 is gone

[3, 23, 5, 12, 5, 6, 67, 8, 456, 8, 4, 9, 12]

In [111]:
y.remove_max()

In [113]:
y  # 456 is gone

[3, 23, 5, 12, 5, 6, 8, 8, 4, 9, 12]

In [120]:
class NewList(list):
    def remove_max(self):
        self.remove(max(self))
    def append_sum(self):
        self.append(sum(self))      

In [122]:
x = NewList([1,2,3])

In [124]:
type(x)

__main__.NewList

In [ ]:
# while max(x) < 10:   # hashed as this cell will run forever since the while condition will always be met!
    x.remove_max()
    x.append_sum()

## **NumPy**
-----------

**NumPy arrays are an additional data type provided by NumPy; used for representing vectors and matrices.   
Unlike dynamically growing python lists size of NumPy arrays are fixed when they're constructed.     
Elements of all NumPy arrays must be of same data type; leading to more efficient and simpler code.    
By default these elements are floating points.**

In [1]:
import numpy as np

In [3]:
zero_vector = np.zeros(5) # to have 5 elements in the vector

In [4]:
zero_vector

array([0., 0., 0., 0., 0.])

In [5]:
zero_matrix = np.zeros((5,3))  # matrix with 5 rows and 3 columns

When creating matrices the input is also one but **has to be a tuple**   
This tuple specifies two things:   
&emsp; &emsp; &emsp; &emsp; **First argument - number of rows in the matrix    
&emsp; &emsp; &emsp; &emsp; Second argument - number of columns in the matrix**

In [6]:
zero_matrix

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

**`np.zeros()`'s elements will always will be zeroes!**

**`np.ones()` will always creates vectors/matrices containing ones**

In [9]:
ones_vector = np.ones(10)

In [11]:
ones_vector

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [13]:
ones_matrix = np.ones((5,5))

In [15]:
ones_matrix

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

**`np.empty` will create vectors and matrices that allocates the required space for the object but does not initialize it; meaning the content of such empty NumPy objects could be anything i.e whatever happens to be in the computer's memory at the location where the array is set up**

In [19]:
empty_vector = np.empty(9)

In [20]:
empty_vector

array([0.000e+000, 0.000e+000, 0.000e+000, 0.000e+000, 0.000e+000,
       7.035e-321, 0.000e+000, 0.000e+000, 0.000e+000])

In [24]:
empty_matrix = np.empty((8,8))

In [25]:
empty_matrix

array([[4.3477777e-322, 0.0000000e+000, 4.9406565e-324, 6.2167845e-317,
        0.0000000e+000, 0.0000000e+000, 0.0000000e+000, 0.0000000e+000],
       [0.0000000e+000, 0.0000000e+000, 0.0000000e+000, 0.0000000e+000,
        0.0000000e+000, 0.0000000e+000, 0.0000000e+000, 0.0000000e+000],
       [0.0000000e+000, 0.0000000e+000, 0.0000000e+000, 0.0000000e+000,
        0.0000000e+000, 0.0000000e+000, 0.0000000e+000, 0.0000000e+000],
       [0.0000000e+000, 0.0000000e+000, 0.0000000e+000, 0.0000000e+000,
        0.0000000e+000, 0.0000000e+000, 0.0000000e+000, 0.0000000e+000],
       [0.0000000e+000, 0.0000000e+000, 0.0000000e+000, 0.0000000e+000,
        0.0000000e+000, 0.0000000e+000, 0.0000000e+000, 0.0000000e+000],
       [0.0000000e+000, 0.0000000e+000, 0.0000000e+000, 0.0000000e+000,
        0.0000000e+000, 0.0000000e+000, 0.0000000e+000, 0.0000000e+000],
       [0.0000000e+000, 0.0000000e+000, 0.0000000e+000, 0.0000000e+000,
        0.0000000e+000, 0.0000000e+000, 0.0000000e+000, 0.

**When dealing with very large arrays and when you know for certain that each element of the array will be updated in future, creating empty NumPy arrays will save some computation time.**

**NumPy arrays can also be created by directly providing the elements by the `np.array()` function. The input is typically a list of objects.**

In [27]:
x = np.array([1,2,3,4,5])

In [29]:
y = np.array([2,4,6,8,10])

In [31]:
x

array([1, 2, 3, 4, 5])

In [33]:
y

array([ 2,  4,  6,  8, 10])

**When creating NumPy matrices (two dimensional NumPy arrays) elements of each row is specified as a list (as nested lists)**

In [46]:
X = np.array([[1,2,3,4,5],  # it is critical to enclose all the lists representing each rows inside an enclosing list
             [3,4,5,6,7],
             [5,6,7,8,9],
             [7,8,9,10,11],
             [9,11,13,15,17]])             

In [47]:
X

array([[ 1,  2,  3,  4,  5],
       [ 3,  4,  5,  6,  7],
       [ 5,  6,  7,  8,  9],
       [ 7,  8,  9, 10, 11],
       [ 9, 11, 13, 15, 17]])

In [48]:
type(X)

numpy.ndarray

### **When having to turn the table (matrix/two dimensional array) sideways; an operation called taking the transpose of a matrix:**  
--------
### **i.e first row becomes the first column, second row the second column, so on and so forth**

In [50]:
X.transpose()  # note the rotations

array([[ 1,  3,  5,  7,  9],
       [ 2,  4,  6,  8, 11],
       [ 3,  5,  7,  9, 13],
       [ 4,  6,  8, 10, 15],
       [ 5,  7,  9, 11, 17]])

In [52]:
t = np.array([[3,6],
              [5,7]])

In [54]:
t

array([[3, 6],
       [5, 7]])

In [56]:
t.transpose()

array([[3, 5],
       [6, 7]])

### **Slicing NumPy arrays**

**Both NumPy arrays and matrices can be sliced.    
Python's indexing applies here as well, when slicing start index is included but the stop index is not!**

**NumPy arrays can be created with 3 or 4 dimensions as well, in such cases colon `:` character is used to in place of a fixed value for an index, which means that array elements corresponding to all values of particular index will be returned.**

In [76]:
x = np.array([1,2,3])  # 1D array
y = np.array([2,4,6])  # 1D array

X = np.array([[1,2,3],
              [4,5,6]])  # 2D array
Y = np.array([[2,4,6],
              [8,10,12]])  # 2D array

**Accessing elements of NumPy arrays**

In [77]:
x[0]  # just like Python's lists

1

In [78]:
x[2]

3

In [79]:
x[0:2]  # slicing

array([1, 2])

In [80]:
x[1:3]

array([2, 3])

In [81]:
X[0]  # returns the first row

array([1, 2, 3])

In [82]:
X[0][0]  # returns the first element of first row

1

In [84]:
X[1][1]  # returns the second element of second row

5

### **Adding NumPy arrays**

In [89]:
x+y  # simple element wise addition

array([3, 6, 9])

In [90]:
X+Y  # arrays of identical dimensions can be added; elements with identical indices are added
# i.e X[0][0] + Y[0][0], X[0][1] + Y[0][1] so on

array([[ 3,  6,  9],
       [12, 15, 18]])

In [3]:
a = np.array([1,2,3,4])
b = np.array([6,7,8])

In [5]:
a + b  # arrays of different dimensions cannot be added, even one dimensional arrays (vectors)

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [6]:
c = np.array([1,2,3,4])

In [7]:
a + c

array([2, 4, 6, 8])

In [18]:
even = np.array([2,4,6,8,10,12,14,16,18,20])  # len = 10

In [19]:
odd = np.array([1,3,5,7,9,11,13,15,17,19])  # len = 10

In [20]:
odd + even

array([ 3,  7, 11, 15, 19, 23, 27, 31, 35, 39])

In [22]:
even[:]  # returns all elements

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [23]:
even[7:]  # returns all elements from index 7

array([16, 18, 20])

In [25]:
even[:4]  # returns all elements upto index 3 - Python excludes last index by default

array([2, 4, 6, 8])

In [27]:
even[:2]  # 1st, 2nd elements

array([2, 4])

In [29]:
even[4:8]  # 4th, 5th, 6th & 7th elements

array([10, 12, 14, 16])

In [31]:
even[1:4] + odd[5:8]

array([15, 19, 23])

In [33]:
X = np.array([[1,2,3],
              [4,5,6]]) 
Y = np.array([[2,4,6],
              [8,10,12]])

In [35]:
X[1]  # 2nd row

array([4, 5, 6])

In [37]:
X[0:2]  # 1st & 2nd rows

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
X[:,1]  # returns 2nd column

array([2, 5])

**Comma separates the specifications for rows and columns in that order.     
In `X[:,2]` `;` means all rows and `2` means 3rd column**

In [41]:
Y[:,1]

array([ 4, 10])

In [43]:
large_array = np.array([[1,2,3,4,5,6,7,8],
                        [2,4,6,8,10,12,14,16],
                        [4,8,12,16,20,24,28,32],
                        [8,16,24,32,40,48,56,64],
                        [16,32,48,64,80,96,112,124],
                        [32,64,96,128,160,192,224,248]])

In [45]:
large_array[:,1]  # second column

array([ 2,  4,  8, 16, 32, 64])

In [47]:
large_array[2,:]  # third row

array([ 4,  8, 12, 16, 20, 24, 28, 32])

In [49]:
large_array[2,2]  # intersect of 3rd row & 3rd column

12

In [50]:
large_array[1:,3:]

array([[  8,  10,  12,  14,  16],
       [ 16,  20,  24,  28,  32],
       [ 32,  40,  48,  56,  64],
       [ 64,  80,  96, 112, 124],
       [128, 160, 192, 224, 248]])

**[`1:,` represents all rows besides first row     
`3:]` represents all columns from the third column**

In [52]:
large_array[3:6,2:5]

array([[ 24,  32,  40],
       [ 48,  64,  80],
       [ 96, 128, 160]])

**`[3:6` specifies 3rd, 4th & 5th rows    
`,2:5]` specifies 2nd, 3rd & 4th columns    
Thus the sliced matrix is the intersect that satisfies both of these conditions.**

### **Caution**
--------------

In [54]:
m = [5,10,15,20]
n = [4,8,12,16]

In [56]:
m + n  # in Python's lists, elements are appended when adding i.e concatanates those two lists

[5, 10, 15, 20, 4, 8, 12, 16]

In [58]:
M = np.array(m)
N = np.array(n)

In [60]:
M + N  # in NumPy arrays element wise addition takes place when two arrays are added

array([ 9, 18, 27, 36])

In [62]:
a = np.array([1,2])
b = np.array([3,4,5])
b[a]

array([4, 5])

**`a = [1,2]` so `b[a]` means `b[1,2]` which represents 2nd & 3rd element of the array.         
Since b is a one dimensional NumPy array and not a list, the `,` separator here does not stand for separating row & column indices but just specifies row indices!**    
**`b[1,2]` just means `b[1:3]`**

In [66]:
b[a] == b[1,2]  # error

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [68]:
b[a] == b[np.array([1,2])]  # voila  NOTE THE DIFFERENCES

array([ True,  True])

In [73]:
b[a] == b[1:3]

array([ True,  True])

In [74]:
b[1:3] == b[np.array([1,2])]

array([ True,  True])

In [76]:
a = np.array([1,2])
b = np.array([3,4,5])
c = b[1:]
b[a] is c  # false because different objects with identical elements

False

In [78]:
b[a] == c  # voila

array([ True,  True])

In [109]:
all(b[a] == c)  # gives a single boolean instead of separate booleans for each index
                # True will be returned only if all booleans are true (multiplication)

True

### **Indexing NumPy arrays**
----------------

**NumPy arrays can be indexed with other arrays or other sequence like objects.**

In [110]:
z1 = np.array([1,3,5,7,9])

In [111]:
z2 = z1 + 1   # 1 added to each element of z1

In [112]:
z2

array([ 2,  4,  6,  8, 10])

In [113]:
index = [0,2,3]

In [114]:
z1[index]   # returns the elements of z1 specified by the list index

array([1, 5, 7])

**Indices of NumPy arrays can also be defined as NumPy arrays.**

In [115]:
ind = np.array([1,3,4])

In [116]:
z1[ind]

array([3, 7, 9])

In [117]:
z2[index]

array([2, 6, 8])

In [118]:
z2[ind]

array([ 4,  8, 10])

**NumPy arrays can also be indexed using logical indices.    
An array consisting of booleans (True & False) can be used for indexing. (Boolean arrays / Logical arrays)**    

In [125]:
array = np.array([2,4,6,8,10,12,14,16,18,20])

In [126]:
array > 6  # returns a boolean array

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [127]:
array >= 6

array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True])

In [128]:
all(array >= 6)  # True will be returned only if all booleans are true

False

In [129]:
array <= 11

array([ True,  True,  True,  True,  True, False, False, False, False,
       False])

**_Using boolean arrays to index NumPy arrays_**

In [131]:
array[array < 10]  # returns elements of NumPy array that satisfy the indexing criteria

array([2, 4, 6, 8])

In [133]:
new_array = array ** 2

In [135]:
array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [136]:
new_array

array([  4,  16,  36,  64, 100, 144, 196, 256, 324, 400], dtype=int32)

In [138]:
new_array[array > 5]

array([ 36,  64, 100, 144, 196, 256, 324, 400], dtype=int32)

**Here `"new_array"` is indexed with a logical vector of a different array `"array"`.   
This is what happens here:**     
       
**`array > 5` is `array([False, False, True, True, True, True, True, True, True, True])` so Python returns the elements of `"new_array"` whose indices are `True` in the indexing array `"array"`.**    
       
**`new_array[array > 5]` = `new_array[[False, False, True, True, True, True, True, True, True, True]]` =   
`new_array[2:]`**

In [144]:
new_array[array > 5] == new_array[[False, False, True, True, True, True, True, True, True, True]]

array([ True,  True,  True,  True,  True,  True,  True,  True])

In [155]:
all(new_array[array > 5] == new_array[[False, False, True, True, True, True, True, True, True, True]])

True

In [159]:
all(new_array[[False, False, True, True, True, True, True, True, True, True]] == new_array[2:])

True

**A logical vector can be constructed from NumPy arrays to index other arrays**

In [160]:
indices = array >= 6

In [162]:
indices  # a logical array

array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True])

In [163]:
array[indices]

array([ 6,  8, 10, 12, 14, 16, 18, 20])

In [164]:
new_array[indices]

array([ 36,  64, 100, 144, 196, 256, 324, 400], dtype=int32)

In [166]:
new_array[indices] == new_array[2:]

array([ True,  True,  True,  True,  True,  True,  True,  True])

In [168]:
all(new_array[indices] == new_array[2:])

True

### **When slicing arrays with `:` the result is a view of original array within the specified indices. And when the elements of slices are modified the original array will also be modified.** 
### **But when slicing arrays with `arrays`/`lists` that have indices separated by commas, returned arrays are copies of original array not a view of original array, thes original array isn't modified when the slices are modified**

In [210]:
array = np.array([5,10,15,20])

In [211]:
sliced_array = array[0:2]   # slicing using colon

In [212]:
sliced_array

array([ 5, 10])

In [213]:
sliced_array[0] = 6  # modifying contents

In [214]:
sliced_array

array([ 6, 10])

In [215]:
array  # 0th element is modified here also!!

array([ 6, 10, 15, 20])

### **Slicing arrays with `arrays`/`lists` as indices**

In [216]:
array = np.array([5,10,15,20,25,30])

In [217]:
index_list = [0,2,4]  # index list

In [218]:
array[index_list]

array([ 5, 15, 25])

In [219]:
new_array = array[index_list]

In [220]:
new_array

array([ 5, 15, 25])

In [221]:
new_array[0] = 7

In [222]:
new_array

array([ 7, 15, 25])

In [223]:
array   #  original array is untouched

array([ 5, 10, 15, 20, 25, 30])

In [224]:
index_array = np.array([0,2,4])  # index array

In [225]:
New_array = array[index_array]

In [226]:
New_array

array([ 5, 15, 25])

In [227]:
New_array[0] = 8

In [228]:
New_array

array([ 8, 15, 25])

In [229]:
array   #  original array is untouched

array([ 5, 10, 15, 20, 25, 30])

## **Building & examining NumPy arrays**

There are few methods to construct arrays with fixed start & end values with the middle elements uniformly spaces between the start & end.  
**`linspace`**

In [237]:
tens = np.linspace(start = 0, stop = 100, num = 11)   # both limits will be included in the array

**Similar to `R`'s seq()**

In [239]:
tens   # evenly spaced

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

**To construct an array with elements spaced evenly on a log scale NumPy's `logspace` is used.**   
### **In `logspace()` the first argument is the log of the starting point!!! If the first element is `10` and an array in `log10` scale is needed the first argument of `np.logspace()` should be `log10` of `10` which is 1!**   
### **Endpoint argument should alse be passed as the log of end value! i.e if the end value is `1000` and `log10` scale is used the endpoint argument should be `log10` of `1000` which is `3`.**

In [248]:
logs = np.logspace(1,2,11)  # 10**1 = 10, 10 ** 2 =100

In [249]:
logs

array([ 10.        ,  12.58925412,  15.84893192,  19.95262315,
        25.11886432,  31.6227766 ,  39.81071706,  50.11872336,
        63.09573445,  79.43282347, 100.        ])

**Creating a base 10 logarithmic array of 20 values between 250 & 1000**

In [250]:
log_array = np.logspace(start = np.log10(250), stop = np.log10(1000), num = 20)

In [253]:
log_array

array([ 250.        ,  268.92264656,  289.27755932,  311.17314737,
        334.72602531,  360.06163438,  387.31491057,  416.6310032 ,
        448.16604807,  482.08799897,  518.57752222,  557.82895888,
        600.05135979,  645.46959897,  694.32557131,  746.87948083,
        803.41122657,  864.22189328,  929.63535501, 1000.        ])

**To find out the shape of arrays (similar to R's `dim()`)**

In [260]:
log_array.shape  # 20 rows no columns

(20,)

In [261]:
large_array = np.array([[1,2,3,4,5,6,7,8],
                        [2,4,6,8,10,12,14,16],
                        [4,8,12,16,20,24,28,32],
                        [8,16,24,32,40,48,56,64],
                        [16,32,48,64,80,96,112,124],
                        [32,64,96,128,160,192,224,248]])

In [262]:
large_array.shape   # 6 rows & 8 columns

(6, 8)

**To find out number of elements in an array**

In [264]:
large_array.size    # 6*8

48

In [265]:
log_array.size

20

**`.size` & `.shape` are not followed by parantheses, as these are data attributes not methods!!**

**Logical operations on arrays**

In [270]:
import random as rd

seq = np.array([rd.uniform(0,1) for i in range(0,1000)])

In [272]:
seq.shape

(1000,)

In [275]:
sum(seq > 0.9)   # only 89 entries out of 1000 are grater than 0.9

83

In [277]:
sum(seq >= 0.1)   # 906 entries out of 1000 are greater than or equal to 0.1

906

### **_NumPy has its own `random()` module!_**

In [281]:
np.random.random(5)   # by default the interval is 0 to 1 

array([0.47276887, 0.01219506, 0.83776761, 0.05067586, 0.95787249])

In [282]:
np.random.random(10)

array([0.60674685, 0.60241287, 0.95608131, 0.79903568, 0.43787754,
       0.54953734, 0.61013414, 0.55582387, 0.46478531, 0.01758654])

In [283]:
x = np.random.random(10)

**`np.any()` to find any of the array's elements satisfy the passed logical condition**

In [284]:
np.any(x > 0.9)

True

**`np.all()` to find out if all the elements of array satisfy the passed logical condition**

In [285]:
np.all(x >= 0.1)

True

#### **Prime numbers are integers that are divisible only by 1 and themselves without remainder**

In [291]:
x = 20
not np.any([x%i == 0 for i in range(2, x)])

False

**`x % i == 0` tests if `x` has a remainder when divided by `i`. If this is `not` `true` for all values strictly between `1` and `x`, it must be prime!**