# Using Python for Research Homework: Week 2

In this homework, we will use the tools we've covered in the past two weeks to create a tic-tac-toe (noughts and crosses) simulator and evaluate basic winning strategies.

### Exercise 1

Tic-tac-toe (or noughts and crosses) is a simple strategy game in which two players take turns placing a mark on a 3x3 board, attempting to make a row, column, or diagonal of three with their mark. In this homework, we will use the tools we've covered in the past two weeks to create a tic-tac-toe simulator and evaluate basic winning strategies.

In the following exercises, we will learn to create a tic-tac-toe board, place markers on the board, evaluate if either player has won, and use this to simulate two basic strategies.

#### Instructions 

- For our tic-tac-toe board, we will use a numpy array with dimension 3 by 3. 
- Make a function `create_board()` that creates such a board with the value of each cell set to the integer `0`.
- Call `create_board()` and store it.

In [31]:
def create_board():
    import numpy as np
    return np.zeros([3,3], dtype = "int")


In [32]:
create_board()

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

### Exercise 2

Players 1 and 2 will take turns changing values of this array from a 0 to a 1 or 2, indicating the number of the player who places a marker there.

#### Instructions 

- Create a function `place(board, player, position)`, where:
    - `player` is the current player (an integer 1 or 2).
    - `position` is a tuple of length 2 specifying a desired location to place their marker.
    - Your function should only allow the current player to place a marker on the board (change the board position to their number) if that position is empty (zero).
- Use `create_board()` to store a board as `board`, and use `place` to have Player 1 place a marker on location `(0, 0)`.

In [5]:
def create_board():
    import numpy as np
    global board   # creates "board" as a global object
    board = np.zeros([3,3], dtype = "int")   # dtype = "int" converts the default float data type to integers

def place(board, player, position):
    import numpy as np
    if player in np.array([1,2]):   # inputs other than 1 & 2 for player will be ignored
        if board[position] == 0:   # checks whether the requested position is empty
            board[position] = int(player)  # placing the number of the player in requested position
        else:
            print("Requested position is already occupied")
    else:
        print("Only two players are allowed in this game")

In [6]:
create_board()

In [7]:
board

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [8]:
place(board,1,(0,0))

In [9]:
board   # voila

array([[1, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

### Exercise 3

In this exercise, we will determine which positions are available to either player for placing their marker.

#### Instructions 
- Create a function `possibilities(board)` that returns a list of all positions (tuples) on the board that are not occupied (0). (Hint: `numpy.where` is a handy function that returns a list of indices that meet a condition.)
- `board` is already defined from previous exercises. Call `possibilities(board)` to see what it returns!

In [10]:
def possibilities(board):
    import numpy as np
    indices = np.where(board == 0)   # finds the row & column indices where the element is 0
    empty = []
    for i in range(0,(len(indices[1]))):    # picking row and column elements indexwise and creating a list of coordinates in the form of tuples
        empty.append((indices[0][i],indices[1][i]))
    return empty

In [11]:
possibilities(board)

[(0, 1), (0, 2), (1, 0), (1, 1), (1, 2), (2, 0), (2, 1), (2, 2)]

### Exercise 4

The next step is for the current player to place a marker among the available positions. In this exercise, we will select an available board position at random and place a marker there.

#### Instructions 

- Write a function `random_place(board, player)` that places a marker for the current player at random among all the available positions (those currently set to 0).
    - Find possible placements with `possibilities(board)`.
    - Select one possible placement at random using `random.choice(selection)`.
- `board` is already defined from previous exercises. Call `random_place(board, player)` to place a random marker for Player 2, and store this as board to update its value.

In [12]:
import random 
random.seed(1)

def random_place(board, player):
    import random 
    random_position = random.choice(possibilities(board))   # random selection from the list of empty coordinates
    board[random_position] = int(player)   # placing the player number on the selected coordinate
    return board

In [13]:
board

array([[1, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [14]:
random_place(board,2)

array([[1, 0, 0],
       [2, 0, 0],
       [0, 0, 0]])

### Exercise 5

We will now have both players place three markers each.

#### Instructions 

- A new `board` is already given. Call `random_place(board, player)` to place three pieces each on board for players 1 and 2.
- Print board to see your result.

In [15]:
random.seed(1)

def create_board():
    import numpy as np
    global board   # creates "board" as a global object
    board = np.zeros([3,3], dtype = "int")   # dtype = "int" converts the default float data type to integers

create_board()

In [16]:
board

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [18]:
def possibilities(board):
    import numpy as np
    indices = np.where(board == 0)   # finds the row & column indices where the element is 0
    empty = []
    for i in range(0,len(indices[1])):    # picking row and column elements indexwise and creating a list of coordinates in the form of tuples
        empty.append((indices[0][i],indices[1][i]))
    return empty

possibilities(board)

[(0, 0), (0, 1), (0, 2), (1, 0), (1, 1), (1, 2), (2, 0), (2, 1), (2, 2)]

In [19]:
def random_place(board, player):
    import random 
    random_position = random.choice(possibilities(board))   # random selection from the list of empty coordinates
    board[random_position] = int(player)   # placing the player number on the selected coordinate
    return board

In [20]:
import numpy as np
turns = np.array([1,2,1,2,1,2])

for player in turns:
        random_place(board,player)

In [21]:
board

array([[2, 2, 1],
       [0, 1, 0],
       [0, 1, 2]])

In [22]:
possibilities(board)

[(1, 0), (1, 2), (2, 0)]

In [23]:
np.where(board == 1)

(array([0, 1, 2], dtype=int64), array([2, 1, 1], dtype=int64))

In [24]:
coordinates = []

for i in range(0,3):
    coordinates.append((np.where(board == 1)[0][i],np.where(board == 1)[1][i]))  

In [25]:
coordinates

[(0, 2), (1, 1), (2, 1)]

### Exercise 6

In the next few exercises, we will make functions that check whether either player has won the game.

#### Instructions 
- Make a function `row_win(board, player)` that takes the player (integer) and determines if any row consists of only their marker. 
    - Have it return `True` if this condition is met and `False` otherwise.
- `board` is already defined from previous exercises. Call `row_win` to check if Player 1 has a complete row.

In [26]:
def row_win(board, player):
    boolean = []
    for i in range(0,3):
        if all(board[i,:] == player):
            boolean.append(True)
        else:
            boolean.append(False)
    return boolean

**`def row_win(board, player):`**     
&emsp; &emsp; **`if np.any(np.all(board==player, axis=1)):`** This checks if any row contains all positions equal to player.             
&emsp; &emsp;&emsp; &emsp; **`return True`            
&emsp; &emsp; `else:`          
&emsp; &emsp;&emsp; &emsp; `return False`**

In [27]:
board

array([[2, 2, 1],
       [0, 1, 0],
       [0, 1, 2]])

In [28]:
row_win(board,1)

[False, False, False]

### Exercise 7

In the next few exercises, we will make functions that verify if either player has won the game.

#### Instructions 
- Make a function `col_win(board, player)` that takes the player (integer) and determines if any column consists of only their marker. 
    - Have it return `True` if this condition is met and `False` otherwise.
- `board` is already defined from previous exercises. Call `col_win` to check if Player 1 has a complete column.

In [29]:
def col_win(board, player):
    boolean = []
    for i in range(0,3):
        if all(board[:,i] == player):
            boolean.append(True)
        else:
            boolean.append(False)
    return boolean

In [30]:
col_win(board,1)

[False, False, False]

**`def col_win(board, player):`**     
&emsp; &emsp; **`if np.any(np.all(board==player, axis=0)):`** This checks if any column contains all positions equal to player.             
&emsp; &emsp;&emsp; &emsp; **`return True`            
&emsp; &emsp; `else:`          
&emsp; &emsp;&emsp; &emsp; `return False`**
             
`axis = 0` is row axis!       
         
**`col_win(board, 1)`      
`False`**

### Exercise 8

In the next few exercises, we will make functions that verify if either player has won the game.

#### Instructions 
- Finally, create a function `diag_win(board, player)` that tests if either diagonal of the board consists of only their marker. Have it return `True` if this condition is met, and `False` otherwise.
- `board` has been slightly modified from a previous exercise. Call `diag_win` to check if Player 2 has a complete diagonal.

In [31]:
board[1,1] = 2

def diag_win(board, player):
    import numpy as np
    if (all(board.diagonal() == player) or all(np.fliplr(board).diagonal() == player) == True):  # fliplr() flips the matrix left-right 
       print("Player",player,"has won the game!")
    else:
        pass

diag_win(board,2)

Player 2 has won the game!


          
&emsp;  **`a = np.array([[0, 1, 2],`           
&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; `[3, 4, 5],`     
&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; `[6, 7, 8]])`**     
    
    
**`np.fliplr(a).diagonal()` &emsp; &emsp; &emsp;   Horizontal flip        
`array([2, 4, 6])`**           
              
**`np.flipud(a).diagonal()` &emsp; &emsp; &emsp;   Vertical flip          
`array([6, 4, 2])`**

### Exercise 9

In the next few exercises, we will make functions that check whether either player has won the game.

#### Instructions 
- Create a function `evaluate(board)` that uses `row_win`, `col_win`, and `diag_win` functions for both players. If one of them has won, return that player's number. If the board is full but no one has won, return -1. Otherwise, return 0.
- `board` is already defined from previous exercises. Call evaluate to see if either player has won the game yet.

In [32]:
def row_win(board,player):
    import numpy as np
    if np.any(np.all(board==player, axis=0)==True):
        return player
    else:
        pass

In [33]:
def col_win(board,player):
    import numpy as np
    if np.any(np.all(board==player, axis=1)==True):
        return player
    else:
        pass

In [34]:
def diag_win(board,player):
    import numpy as np
    if np.all(board.diagonal()==player)==True:
        return player
    elif np.all(np.fliplr(board).diagonal()==player)==True:
        return player
    else:
        pass        

In [35]:
board

array([[2, 2, 1],
       [0, 2, 0],
       [0, 1, 2]])

In [36]:
def evaluate(board):
    import numpy as np
    winner = 0
    for player in [1, 2]:
        if np.any(np.array([row_win(board,player) ,col_win(board,player) ,diag_win(board,player)]) == player):
            return player
        else:
            pass
    if np.all(board != 0) and winner == 0:  # if board isn't empty and winner = 0
        winner = -1
    return winner

In [37]:
evaluate(board)  # voila

2

row_win(board,player) or col_win(board,player) or diag_win(board,player) == Player

### Exercise 10

In this exercise, we will use all the functions we have made to simulate an entire game.

#### Instructions 

- `create_board()`, `random_place(board, player)`, and `evaluate(board)` have been created in previous exercises. Create a function `play_game()` that:
    - Creates a board.
    - Alternates taking turns between two players (beginning with Player 1), placing a marker during each turn.
    - Evaluates the board for a winner after each placement.
    - Continues the game until one player wins (returning 1 or 2 to reflect the winning player), or the game is a draw (returning -1).
- Call play_game 1000 times, and store the results of the game in a list called `results`.

In [38]:
random.seed(1)

def play_game():
    create_board()  # creates a 3x3 empty board
    while evaluate(board) == 0:  # while no one has won yet 
        for player in (1,2):
            if len(possibilities(board)) != 0:  # if the board isn't filled yet
                random_place(board, player)
    return evaluate(board)   # returns who has won
        
results = []    

for i in range(0,1000):
    results.append(play_game())

In [39]:
results

[1,
 2,
 1,
 1,
 1,
 1,
 2,
 1,
 -1,
 1,
 1,
 2,
 -1,
 2,
 -1,
 1,
 1,
 1,
 2,
 1,
 1,
 -1,
 -1,
 2,
 2,
 2,
 1,
 1,
 1,
 2,
 1,
 2,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 -1,
 2,
 -1,
 1,
 2,
 2,
 1,
 1,
 1,
 1,
 2,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 -1,
 1,
 -1,
 2,
 1,
 -1,
 -1,
 2,
 1,
 2,
 1,
 1,
 -1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 -1,
 1,
 1,
 -1,
 -1,
 1,
 2,
 2,
 -1,
 1,
 1,
 1,
 1,
 -1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 1,
 1,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 2,
 -1,
 1,
 -1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 -1,
 1,
 -1,
 1,
 1,
 1,
 1,
 2,
 2,
 1,
 1,
 1,
 2,
 2,
 1,
 -1,
 1,
 1,
 2,
 1,
 2,
 1,
 2,
 2,
 1,
 2,
 -1,
 1,
 2,
 -1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 1,
 2,
 2,
 1,
 -1,
 2,
 1,
 1,
 1,
 2,
 1,
 1,
 2,
 2,
 1,
 2,
 2,
 1,
 1,
 1,
 2,
 -1,
 2,
 1,
 -1,
 2,
 1,
 1,
 1,
 2,
 1,
 -1,
 1,
 1,
 1,
 1,
 1,
 -1,
 2,
 2,
 1,
 -1,
 1,
 2,
 1,
 1,
 2,
 2,
 2,
 1

In [40]:
len(results)

1000

In [41]:
results.count(1)        # correct is 591

569

random.seed(1)

def play_game():
    board = create_board()
    winner = 0
    while winner == 0:
        for player in [1, 2]:
            random_place(board, player)
            winner = evaluate(board)
            if winner != 0:
                break
    return winner

results = [play_game() for i in range(1000)]
results.count(1)
591

#### Exercise 11

In the previous exercise, we see that when guessing at random, it's better to go first, as expected. Let's see if Player 1 can improve their strategy. 

#### Instructions 
- Create a function `play_strategic_game()`, where Player 1 always starts with the middle square, and otherwise both players place their markers randomly.
- Call `play_strategic_game` 1000 times.

In [42]:
random.seed(1)    # correct is 716

# write your code here


          random.seed(1)

def play_strategic_game():
    board, winner = create_board(), 0
    board[1,1] = 1
    while winner == 0:
        for player in [2,1]:
            random_place(board, player)
            winner = evaluate(board)
            if winner != 0:
                break
    return winner

results = [play_strategic_game() for i in range(1000)]
results.count(1)
716