In [73]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import datetime
from collections import Counter

In [3]:
accelerometer_data = pd.read_csv("C:\\Users\\Anoba\\Documents\\Python\\Using_Python_for_Research\\Final_project\\train_time_series.csv")

In [4]:
accelerometer_data.head()

Unnamed: 0      timestamp                 UTC time accuracy         x  \
0       20586  1565109930787  2019-08-06T16:45:30.787  unknown -0.006485   
1       20587  1565109930887  2019-08-06T16:45:30.887  unknown -0.066467   
2       20588  1565109930987  2019-08-06T16:45:30.987  unknown -0.043488   
3       20589  1565109931087  2019-08-06T16:45:31.087  unknown -0.053802   
4       20590  1565109931188  2019-08-06T16:45:31.188  unknown -0.054031   

          y         z  
0 -0.934860 -0.069046  
1 -1.015442  0.089554  
2 -1.021255  0.178467  
3 -0.987701  0.068985  
4 -1.003616  0.126450

In [5]:
accelerometer_data = pd.read_csv("C:\\Users\\Anoba\\Documents\\Python\\Using_Python_for_Research\\Final_project\\train_time_series.csv")

In [6]:
activity_labels = pd.read_csv("C:\\Users\\Anoba\\Documents\\Python\\Using_Python_for_Research\\Final_project\\train_labels.csv")

**encoding: 1 = standing, 2 = walking, 3 = stairs down, 4 = stairs up.**   
**Because the accelerometers are sampled at high frequency, the labels in train_labels.csv are only provided for every 10th observation in train_time_series.csv.**

In [7]:
activity_labels.shape

(375, 4)

In [8]:
accelerometer_data.shape  # dimensions of the dataframe

(3744, 7)

In [9]:
acc_data = accelerometer_data.iloc[range(3,accelerometer_data.shape[0],10)]  # extracting the rows for which labels are available

In [10]:
acc_data = acc_data.drop(columns=["UTC time","accuracy"])  # selecting the needed columns

In [11]:
acc_data = acc_data.reset_index().drop("index", axis=1)

In [17]:
acc_data

Unnamed: 0      timestamp         x         y         z
0         20589  1565109931087 -0.053802 -0.987701  0.068985
1         20599  1565109932090  0.013718 -0.852371 -0.000870
2         20609  1565109933092  0.145584 -1.007843 -0.036819
3         20619  1565109934094 -0.099380 -1.209686  0.304489
4         20629  1565109935097  0.082794 -1.001434 -0.025375
..          ...            ...       ...       ...       ...
370       24289  1565110302030 -0.641953 -1.469177  0.301041
371       24299  1565110303032 -0.171616 -0.366074 -0.059082
372       24309  1565110304034  0.401810 -1.077698  0.258911
373       24319  1565110305037  0.330338 -1.470062  0.303894
374       24329  1565110306039  0.689346 -0.991043  0.034973

[375 rows x 5 columns]

In [12]:
acc_data[["x","y","z"]].iloc[0]

x   -0.053802
y   -0.987701
z    0.068985
Name: 0, dtype: float64

In [13]:
acc_data[["x","y","z"]].iloc[0]**2

x    0.002895
y    0.975554
z    0.004759
Name: 0, dtype: float64

In [14]:
np.sum(acc_data[["x","y","z"]].iloc[0]**2)

0.983207723358646

In [15]:
acc_data.iloc[374]

Unnamed: 0    2.432900e+04
timestamp     1.565110e+12
x             6.893463e-01
y            -9.910431e-01
z             3.497314e-02
Name: 374, dtype: float64

In [16]:
euclidean_dist = [] 
#for 

SyntaxError: invalid syntax (Temp/ipykernel_9712/443298061.py, line 2)

In [19]:
activity_labels = activity_labels.drop(columns=["UTC time"])

In [20]:
activity_labels

Unnamed: 0      timestamp  label
0         20589  1565109931087      1
1         20599  1565109932090      1
2         20609  1565109933092      1
3         20619  1565109934094      1
4         20629  1565109935097      1
..          ...            ...    ...
370       24289  1565110302030      4
371       24299  1565110303032      4
372       24309  1565110304034      4
373       24319  1565110305037      4
374       24329  1565110306039      4

[375 rows x 3 columns]

In [21]:
acc_data

Unnamed: 0      timestamp         x         y         z
0         20589  1565109931087 -0.053802 -0.987701  0.068985
1         20599  1565109932090  0.013718 -0.852371 -0.000870
2         20609  1565109933092  0.145584 -1.007843 -0.036819
3         20619  1565109934094 -0.099380 -1.209686  0.304489
4         20629  1565109935097  0.082794 -1.001434 -0.025375
..          ...            ...       ...       ...       ...
370       24289  1565110302030 -0.641953 -1.469177  0.301041
371       24299  1565110303032 -0.171616 -0.366074 -0.059082
372       24309  1565110304034  0.401810 -1.077698  0.258911
373       24319  1565110305037  0.330338 -1.470062  0.303894
374       24329  1565110306039  0.689346 -0.991043  0.034973

[375 rows x 5 columns]

In [22]:
data = pd.concat([acc_data, activity_labels["label"]],axis=1, ignore_index=False)

In [23]:
data

Unnamed: 0      timestamp         x         y         z  label
0         20589  1565109931087 -0.053802 -0.987701  0.068985      1
1         20599  1565109932090  0.013718 -0.852371 -0.000870      1
2         20609  1565109933092  0.145584 -1.007843 -0.036819      1
3         20619  1565109934094 -0.099380 -1.209686  0.304489      1
4         20629  1565109935097  0.082794 -1.001434 -0.025375      1
..          ...            ...       ...       ...       ...    ...
370       24289  1565110302030 -0.641953 -1.469177  0.301041      4
371       24299  1565110303032 -0.171616 -0.366074 -0.059082      4
372       24309  1565110304034  0.401810 -1.077698  0.258911      4
373       24319  1565110305037  0.330338 -1.470062  0.303894      4
374       24329  1565110306039  0.689346 -0.991043  0.034973      4

[375 rows x 6 columns]

In [52]:
test = pd.read_csv("C:\\Users\\Anoba\\Documents\\Python\\Using_Python_for_Research\\Final_project\\test_time_series.csv")

In [53]:
test = test.drop(columns=["UTC time","accuracy"])

In [54]:
test_label = pd.read_csv("C:\\Users\\Anoba\\Documents\\Python\\Using_Python_for_Research\\Final_project\\test_labels.csv")

In [55]:
test = test.iloc[range(9,1250,10)]

In [56]:
test = test.reset_index().drop("index",axis=1)
test

Unnamed: 0      timestamp         x         y         z
0         24339  1565110307041  0.098282 -0.833771  0.118042
1         24349  1565110308043  0.348465 -0.946701 -0.051041
2         24359  1565110309046  0.377335 -0.849243 -0.026474
3         24369  1565110310048  0.110077 -0.520325  0.312714
4         24379  1565110311050  0.283478 -0.892548 -0.085876
..          ...            ...       ...       ...       ...
120       25539  1565110427366 -0.043915 -0.242416  0.068802
121       25549  1565110428369  0.118271 -1.212097  0.357468
122       25559  1565110429371  0.667404 -0.978851  0.171906
123       25569  1565110430373  0.371384 -1.021927 -0.244446
124       25579  1565110431376 -0.089462 -0.734573 -0.100876

[125 rows x 5 columns]

In [57]:
test_label

Unnamed: 0      timestamp                 UTC time  label
0         24339  1565110307041  2019-08-06T16:51:47.041    NaN
1         24349  1565110308043  2019-08-06T16:51:48.043    NaN
2         24359  1565110309046  2019-08-06T16:51:49.046    NaN
3         24369  1565110310048  2019-08-06T16:51:50.048    NaN
4         24379  1565110311050  2019-08-06T16:51:51.050    NaN
..          ...            ...                      ...    ...
120       25539  1565110427366  2019-08-06T16:53:47.366    NaN
121       25549  1565110428369  2019-08-06T16:53:48.369    NaN
122       25559  1565110429371  2019-08-06T16:53:49.371    NaN
123       25569  1565110430373  2019-08-06T16:53:50.373    NaN
124       25579  1565110431376  2019-08-06T16:53:51.376    NaN

[125 rows x 4 columns]

In [58]:
from sklearn.neighbors import KNeighborsClassifier

In [59]:
neigh = KNeighborsClassifier(n_neighbors=3)
model = neigh.fit(data[["x","y","z"]], data.label)

In [60]:
knn_predictions1 = model.predict(test[["x","y","z"]])

In [61]:
knn_predictions1

array([1, 2, 2, 2, 1, 2, 4, 4, 2, 2, 3, 3, 2, 2, 2, 3, 2, 3, 1, 2, 2, 3,
       2, 2, 2, 3, 2, 2, 2, 4, 2, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 3, 4, 2, 2, 2, 2, 1, 3, 2, 3, 2,
       3, 3, 2, 2, 2, 2, 2, 3, 3, 2, 2, 2, 4, 2, 2, 3, 2, 3, 3, 3, 3, 3,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 3, 2, 2, 3, 2, 2, 1, 2, 2,
       2, 2, 1, 4, 2, 2, 2, 2, 2, 2, 2, 2, 4, 2, 2], dtype=int64)

In [62]:
len(knn_predictions1)

125

In [63]:
neigh = KNeighborsClassifier(n_neighbors=2)
model = neigh.fit(data[["x","y","z"]], data.label)
knn_predictions2 = model.predict(test[["x","y","z"]])
knn_predictions2

array([1, 2, 2, 2, 1, 2, 2, 3, 2, 2, 3, 3, 2, 2, 2, 1, 2, 3, 2, 2, 2, 3,
       1, 2, 1, 3, 2, 2, 2, 2, 2, 3, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 3, 3, 2, 2, 2, 2, 1, 3, 2, 2, 2,
       3, 3, 2, 2, 2, 2, 2, 3, 2, 2, 2, 2, 2, 2, 2, 3, 2, 3, 2, 3, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 2, 2, 2, 2, 2, 1, 2, 2,
       2, 2, 2, 3, 2, 2, 2, 2, 2, 3, 2, 2, 3, 2, 2], dtype=int64)

In [64]:
np.mean(knn_predictions1 == knn_predictions2)

0.824

**The best value for k in knn predictions is the square root of test samples ($\sqrt{N}$)**

In [65]:
neigh = KNeighborsClassifier(n_neighbors=11)
model = neigh.fit(data[["x","y","z"]], data.label)
knn_predictions = model.predict(test[["x","y","z"]])
knn_predictions

array([2, 2, 2, 3, 2, 2, 3, 3, 2, 2, 3, 3, 1, 2, 2, 2, 2, 3, 2, 2, 2, 2,
       2, 2, 2, 3, 2, 2, 2, 2, 1, 2, 2, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 3, 4, 2, 3, 2, 2, 1, 2, 2, 3, 2,
       3, 3, 4, 3, 2, 2, 2, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 2, 2, 2, 2, 2, 2, 2, 2,
       4, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

In [66]:
np.sqrt(125)

11.180339887498949

In [68]:
train = [ tuple(data[["x","y","z"]].iloc[i]) for i in range(0,375) ]

In [79]:
train[0]

(-0.053802490234375, -0.987701416015625, 0.0689849853515625)

In [70]:
test = [ tuple(test[["x","y","z"]].iloc[i]) for i in range(0,125) ]

In [80]:
test[0]

(0.0982818603515625, -0.833770751953125, 0.1180419921875)

In [78]:
#distance(train,test)

In [95]:
def distance(p1,p2):
    """Finds the Euclidean distance between the two supplied three dimensional coordinates"""
    import numpy as np
    a = np.array(p1)
    b = np.array(p2)
    return np.sqrt(np.sum(np.power(a-b, 2)))

In [96]:
def nearest_neighbour(p,points,k=5):
    import numpy as np
    """Takes an unknown point - p, existing dataset - points and 
    the needed number of nearest neighbours - k to return k number of nearest
    neighbours to the unknown point p"""
    distances = np.zeros(len(points))
    for i in range(0, len(distances)):
        distances[i] = distance(p, points[i])
    return np.argsort(distances)[0:k] # returns the indices of k nearest neighbours

In [97]:
def majority_vote(sequence_object):
    import random
    vote_counts = dict()
    highest_f = []  # in case multiple elements have the highest frequency
    for vote in sequence_object:
        if vote in vote_counts:
            vote_counts[vote] += 1
        else:
            vote_counts[vote] = 1
    max_vote_count = max(vote_counts.values())
    for vote,count in vote_counts.items():
        if count == max_vote_count:  # if the selected frequency is that of the vote with maximum frequency
            highest_f.append(vote)
    return random.choice(highest_f) # when there are many elements with highest frequencies, randomly selecting any one will be good enough

In [98]:
def kNN_predict(p,points,outcomes,k=5):  # here points, outcomes are the training datasets
    ind = nearest_neighbour(p,points,k)
    return majority_vote(outcomes[ind])

In [99]:
for t in test:
    kNN_predict(t,train,np.array(data.label),11)